name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "$SSH_PRIVATE_KEY"
      - name: Connect to server and pull
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker commit -p my-espocrm "$(date "+%Y-%m-%d_%H-%M-%S")_my-espocrm"
            docker commit -p mysql "$(date "+%Y-%m-%d_%H-%M-%S")_mysql"
          ENDSSH
      - name: cleanup
        run: rm -rf ~/.ssh