name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push changes to server
    runs-on: ubuntu-latest

    steps:

      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "$SSH_PRIVATE_KEY"

      - name: Set container backup names
        id: backup_names
        run: |
          echo "ESPOCRM_CONTAINER_BK=$(date "+%Y-%m-%d_%H-%M-%S")_${{ secrets.ESPOCRM_CONTAINER_NAME }}" >> "$GITHUB_OUTPUT"
          echo "MYSQL_CONTAINER_BK=$(date "+%Y-%m-%d_%H-%M-%S")_${{ secrets.MYSQL_CONTAINER_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Connect to server and backup the containers
        id: backup
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker commit -p ${{ secrets.ESPOCRM_CONTAINER_NAME }} ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
            docker commit -p ${{ secrets.MYSQL_CONTAINER_NAME }} ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}
          ENDSSH

      - name: Connect to server, pull in code changes, migrate database schema, set file permissions
        id: docker_container_actions
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} git checkout ${{ secrets.MASTER_BRANCH }}
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} git pull origin ${{ secrets.MASTER_BRANCH }}
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} php rebuild.php
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} chown -R www-data .
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} chgrp -R www-data .
          ENDSSH

      - name: Restore the backup container
        if: (steps.docker_container_actions.outcome == 'success') && (steps.backup.outcome == 'success')
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
          echo ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}

      - name: Cleanup
        run: rm -rf ~/.ssh