name: Test Unit

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      espocrm-version:
        required: true
        type: string

jobs:
  test:
    name: Unit Tests
    runs-on: ${{ inputs.runs-on }}
    steps:

    - name: Checkout EspoCRM
      uses: actions/checkout@v4
      with:
        repository: espocrm/espocrm
        ref: ${{ inputs.espocrm-version }}

    - name: Checkout customisations
      uses: actions/checkout@v4
      with:
        path: './cva_de_duplication_extension'

    - name: Create the extension zip
      run: |
        zip -r cva_de_duplication_extension.zip ./cva_de_duplication_extension/*
        rm -r ./cva_de_duplication_extension/

    - name: Install the extension
      run: |
        php command.php extension --file="cva_de_duplication_extension.zip"

    - name: Setup PHP with Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        ini-values: memory_limit=1024M

    - name: Composer install
      run: composer install

    - name: Static analysis
      run: vendor/bin/phpstan

    - name: Unit testing
      run: vendor/bin/phpunit tests/unit